### ISSUE TITLE
Ustalenie miejsca kolejnego spotkania na dzień 12 listopada.

### ISSUE THREAD

**Issue by alexiej** [dataworkshop/dw-poznan-project#3]
Propozycje (godzina od 18:00 do 20:00):

- Open Space, Malta
- Open Space Posnania

Ustalono że spotkamy się 12-go listopadą w strefie nauki i pracy galerii Malta: http://galeriamalta.pl/strefa-nauki-i-pracy-2420/, o godzinie: 18:30 - 20:30. Agenda
- Data Engineering czyli jak połączyć dane ulubionych filmweb i IMDB
- Wykresy, czyli co pokazać na wykresach
- Druga część. Przedstawię metody testowania aplikacji :slightly_smiling_face: (edited)

**Comment by krzysztofho** [comment]
Ja proponuję Maltę, bo mniejsze szanse, że ktoś nam będzie przeszkadzał.

**Comment by alexiej** [comment]
Ustalone że będzie to Office Space w galerii,  godzina: 18:30, dnia: 12 listopada 2019,
